### ISSUE TITLE
Shutdown in El capitan

### ISSUE THREAD

**Issue by michaelspeed** [Kaijun/Acer-V5-573G-Hackintosh#31]
anyone go the shutdown working?
coz mine is not. even if i shutdown the keyboard is still lit.
evoreboot.kext gives me kernel panic

**Comment by Silveryard** [comment]
I do have the same problem. Can´t shut down. Power LED and Keyboard are still lit.

**Comment by michaelspeed** [comment]
just upgraded the ram 12GB. can you tell me what to upgrade in the clover config

**Comment by Silveryard** [comment]
Sorry i can´t. Still have 8GB (currently waiting for my wifi module as the wifi stick broke with 10.11).
But the shutdown problem is quite annoying and I may invest some time digging deeper.

**Comment by michaelspeed** [comment]
i changed the smbios to macbook pro 15-inch with 16 gigs, at least that fixed some ram issue. did u try fix shutdown in the clover config?
i backed up my clover config then formatted the efi partition and the reinstalled clover used fix shutdown. now it shoutdowns ok

**Comment by michaelspeed** [comment]
Oops i messed with the memory option in clover configuration now i have 20gb ram. cannot figure out.

here is the plist can someone tell me whats wrong with the memory option

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ACPI</key>
	<dict>
		<key>DSDT</key>
		<dict>
			<key>Debug</key>
			<false/>
			<key>DropOEM_DSM</key>
			<false/>
			<key>Fixes</key>
			<dict>
				<key>FixDisplay_0100</key>
				<true/>
				<key>FixSATA_0400</key>
				<true/>
				<key>FixShutdown_0004</key>
				<true/>
			</dict>
			<key>Name</key>
			<string>DSDT.aml</string>
			<key>ReuseFFFF</key>
			<false/>
		</dict>
		<key>ResetAddress</key>
		<string>0x0CF9</string>
		<key>ResetValue</key>
		<string>0x06</string>
		<key>SSDT</key>
		<dict>
			<key>DropOem</key>
			<true/>
			<key>Generate</key>
			<false/>
		</dict>
	</dict>
	<key>Boot</key>
	<dict>
		<key>Arguments</key>
		<string>-v kext-dev-mode=1 rootless=0 IGPEnabler=Yes GraphicsEnabler=No</string>
		<key>Debug</key>
		<false/>
		<key>DefaultVolume</key>
		<string>OS X</string>
		<key>Legacy</key>
		<string>PBR</string>
		<key>Secure</key>
		<false/>
		<key>Timeout</key>
		<integer>1</integer>
		<key>XMPDetection</key>
		<string>Yes</string>
	</dict>
	<key>Devices</key>
	<dict>
		<key>Audio</key>
		<dict>
			<key>Inject</key>
			<string>3</string>
		</dict>
		<key>FakeID</key>
		<dict>
			<key>ATI</key>
			<string>0x0</string>
			<key>IMEI</key>
			<string>0x0</string>
			<key>IntelGFX</key>
			<string>0x04128086</string>
			<key>LAN</key>
			<string>0x0</string>
			<key>NVidia</key>
			<string>0x0</string>
			<key>SATA</key>
			<string>0x0</string>
			<key>WIFI</key>
			<string>0x0</string>
			<key>XHCI</key>
			<string>0x0</string>
		</dict>
		<key>USB</key>
		<dict>
			<key>FixOwnership</key>
			<false/>
			<key>Inject</key>
			<false/>
		</dict>
	</dict>
	<key>DisableDrivers</key>
	<array>
		<string>Nothing</string>
	</array>
	<key>GUI</key>
	<dict>
		<key>Hide</key>
		<array>
			<string>BOOTX64.EFI</string>
			<string>Windows</string>
		</array>
		<key>Language</key>
		<string>en:0</string>
		<key>Mouse</key>
		<dict>
			<key>DoubleClick</key>
			<integer>500</integer>
			<key>Enabled</key>
			<false/>
			<key>Mirror</key>
			<false/>
			<key>Speed</key>
			<integer>8</integer>
		</dict>
		<key>Scan</key>
		<dict>
			<key>Entries</key>
			<true/>
			<key>Legacy</key>
			<false/>
			<key>Tool</key>
			<true/>
		</dict>
		<key>Theme</key>
		<string>bluemac</string>
	</dict>
	<key>Graphics</key>
	<dict>
		<key>Inject</key>
		<dict>
			<key>ATI</key>
			<false/>
			<key>Intel</key>
			<true/>
			<key>NVidia</key>
			<false/>
		</dict>
		<key>NvidiaSingle</key>
		<false/>
		<key>ig-platform-id</key>
		<string>0x0a260006</string>
	</dict>
	<key>KernelAndKextPatches</key>
	<dict>
		<key>AppleRTC</key>
		<false/>
		<key>AsusAICPUPM</key>
		<false/>
		<key>Debug</key>
		<false/>
		<key>KernelCpu</key>
		<false/>
		<key>KernelHaswellE</key>
		<false/>
		<key>KernelLapic</key>
		<false/>
		<key>KernelPm</key>
		<true/>
		<key>KextsToPatch</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>External icons patch</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				RXh0ZXJuYWw=
				</data>
				<key>Name</key>
				<string>AppleAHCIPort</string>
				<key>Replace</key>
				<data>
				SW50ZXJuYWw=
				</data>
			</dict>
			<dict>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				gxnUEQ==
				</data>
				<key>Name</key>
				<string>AppleHDA</string>
				<key>Replace</key>
				<data>
				AAAAAA==
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Expect 2 matches</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				hAjsEA==
				</data>
				<key>Name</key>
				<string>AppleHDA</string>
				<key>Replace</key>
				<data>
				AAAAAA==
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Expect 2 matches</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				hBnUEQ==
				</data>
				<key>Name</key>
				<string>AppleHDA</string>
				<key>Replace</key>
				<data>
				ggLsEA==
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Expect 2 matches</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				hQjsEA==
				</data>
				<key>Name</key>
				<string>AppleHDA</string>
				<key>Replace</key>
				<data>
				AAAAAA==
				</data>
			</dict>
		</array>
	</dict>
	<key>RtVariables</key>
	<dict>
		<key>BooterConfig</key>
		<string>0x28</string>
		<key>CsrActiveConfig</key>
		<string>0x3</string>
		<key>MLB</key>
		<string>xxx</string>
		<key>ROM</key>
		<string>xxx</string>
	</dict>
	<key>SMBIOS</key>
	<dict>
		<key>BiosReleaseDate</key>
		<string>10/18/13</string>
		<key>BiosVendor</key>
		<string>Apple Inc.</string>
		<key>BiosVersion</key>
		<string>MBP112.88Z.0138.B02.1310181745</string>
		<key>Board-ID</key>
		<string>Mac-3CBD00234E554E41</string>
		<key>BoardManufacturer</key>
		<string>Apple Inc.</string>
		<key>BoardType</key>
		<integer>10</integer>
		<key>ChassisAssetTag</key>
		<string>MacBook-Aluminum</string>
		<key>ChassisManufacturer</key>
		<string>Apple Inc.</string>
		<key>ChassisType</key>
		<string>08</string>
		<key>Family</key>
		<string>MacBook Pro</string>
		<key>Manufacturer</key>
		<string>Apple Inc.</string>
		<key>Memory</key>
		<dict>
			<key>Channels</key>
			<integer>2</integer>
			<key>Modules</key>
			<array>
				<dict>
					<key>Frequency</key>
					<integer>1600</integer>
					<key>Part</key>
					<string>C0001403</string>
					<key>Serial</key>
					<string>00001001</string>
					<key>Size</key>
					<integer>4096</integer>
					<key>Slot</key>
					<string>1</string>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>Samsung</string>
				</dict>
				<dict>
					<key>Frequency</key>
					<string>1600</string>
					<key>Part</key>
					<string>KHDKHDJ98789</string>
					<key>Serial</key>
					<string>DKJJKDJKD87899798</string>
					<key>Size</key>
					<string>4096</string>
					<key>Slot</key>
					<string>1</string>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>KIngston</string>
				</dict>
				<dict>
					<key>Frequency</key>
					<integer>1600</integer>
					<key>Part</key>
					<string>C0001404</string>
					<key>Serial</key>
					<string>00001002</string>
					<key>Size</key>
					<integer>4096</integer>
					<key>Slot</key>
					<integer>0</integer>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>Samsung</string>
				</dict>
				<dict>
					<key>Frequency</key>
					<string>1600</string>
					<key>Part</key>
					<string>JKJSDKHK89894</string>
					<key>Serial</key>
					<string>ADJHUHJFF674</string>
					<key>Size</key>
					<string>4096</string>
					<key>Slot</key>
					<string>0</string>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>Kingston</string>
				</dict>
				<dict>
					<key>Frequency</key>
					<string>1600</string>
					<key>Part</key>
					<string>KDFH3265632</string>
					<key>Serial</key>
					<string>DJKIUDX4499</string>
					<key>Size</key>
					<string>4096</string>
					<key>Slot</key>
					<string>0</string>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>Kingston</string>
				</dict>
				<dict>
					<key>Frequency</key>
					<string>1600</string>
					<key>Part</key>
					<string>HJBFJD7889799</string>
					<key>Serial</key>
					<string>DKKJHJKD87787090</string>
					<key>Size</key>
					<string>8192</string>
					<key>Slot</key>
					<string>2</string>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>HP</string>
				</dict>
				<dict>
					<key>Frequency</key>
					<string>1600</string>
					<key>Part</key>
					<string>HDHLKDHH8980080</string>
					<key>Serial</key>
					<string>KDGKSJKDKG987897</string>
					<key>Size</key>
					<string>8192</string>
					<key>Slot</key>
					<string>1</string>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>HP</string>
				</dict>
				<dict>
					<key>Frequency</key>
					<string>1600</string>
					<key>Part</key>
					<string>KJFGDBJ8932</string>
					<key>Serial</key>
					<string>DJKJKDE8374</string>
					<key>Size</key>
					<string>8192</string>
					<key>Slot</key>
					<string>1</string>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>HP</string>
				</dict>
			</array>
		</dict>
		<key>Mobile</key>
		<true/>
		<key>ProductName</key>
		<string>MacBookPro11,2</string>
		<key>SerialNumber</key>
		<string>C02KW6MJFD56</string>
		<key>Trust</key>
		<false/>
		<key>Version</key>
		<string>1.0</string>
	</dict>
	<key>SystemParameters</key>
	<dict>
		<key>InjectKexts</key>
		<string>Detect</string>
		<key>InjectSystemID</key>
		<true/>
	</dict>
</dict>
</plist>
`

**Comment by Silveryard** [comment]
Does shutdown work now or only reboot?

**Comment by michaelspeed** [comment]
if i reboot then it shutdowns.......

**Comment by Silveryard** [comment]
So at least you are able to shutdown ^^ This could help finding a final solution for the problem

**Comment by michaelspeed** [comment]
i don't know . i just ticked the fix shutdown in clover

**Comment by michaelspeed** [comment]
i fixed the ram issue will give an update

**Comment by zwj0571** [comment]
so,the branch for EI with i5 model has not solve "shutdown" problem? I think maybe we can use 
legacy mode to boot osx

**Comment by Kaijun** [comment]
How to fix of shutdown in DSDT was already written in my [DSDT Tutorial](https://github.com/Kaijun/Acer-V5-573g-DSDT), in addition, the weird shutdown behaviour was also fixed as described in #6
